# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20171202_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='pubtime',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='endday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='endmonth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='endyear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='isCompleted',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
